/**
 * Media storage — where an uploaded file actually goes.
 * ---------------------------------------------------------------------------
 * Two drivers behind one interface, chosen by UPLOAD_DRIVER:
 *
 *   local       writes under env.uploadDir, served back from /uploads
 *   cloudinary  uploads to Cloudinary, database stores the HTTPS URL
 *
 * Both return the same shape — `{ url, publicId }` — and both accept the same
 * `remove(url)`. That is the whole point: the catalogue code decides when an
 * image should exist and when it should be destroyed, and never has to know
 * which of the two is running. Switching drivers is an environment change.
 *
 * What the database stores is still just A URL string. No schema changed for
 * Cloudinary. A local record keeps its relative `/uploads/2026-08/ab…png`, a
 * Cloudinary record holds `https://res.cloudinary.com/…`, and both render
 * correctly because the client resolves relative paths against the API origin
 * and leaves absolute ones alone (see frontend/src/lib/media.js).
 *
 * The public ID is derived from the URL rather than stored in a new column.
 * A Cloudinary delivery URL contains the public id by construction, so an image
 * uploaded today and an image uploaded before this file existed are both
 * deletable — and no migration is needed to make old rows manageable.
 */
import path from 'node:path';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';

import { env } from '../../config/env.config.js';
import { logger } from '../utils/logger.js';

const UPLOAD_ROOT = env.uploadDir;

/** True when the driver in use is Cloudinary. */
export const isCloudinary = env.UPLOAD_DRIVER === 'cloudinary';

/**
 * Cloudinary's REST API, called directly rather than through its SDK.
 *
 * The whole surface this application needs is two signed POSTs — upload and
 * destroy — and Node has had `fetch`, `FormData` and `Blob` built in since 18.
 * A dependency to wrap that is a dependency to audit, update and trust with an
 * API secret, for roughly forty lines of code.
 *
 * The secret is never transmitted. Cloudinary authenticates a request by its
 * signature: the parameters, sorted by name and joined, with the secret
 * appended and the whole thing hashed. The secret proves we knew it without
 * ever crossing the wire.
 */
const API_BASE = 'https://api.cloudinary.com/v1_1';

/**
 * Sign a parameter set the way Cloudinary requires.
 *
 * Sorted by name, `k=v` joined with `&`, secret appended, SHA-1 hex. `file`,
 * `api_key` and `resource_type` are excluded by the specification — including
 * any of them produces a signature Cloudinary rejects with a message that does
 * not say which parameter was wrong.
 */
function signParams(params, secret) {
  const canonical = Object.keys(params)
    .filter((key) => params[key] !== undefined && params[key] !== null && params[key] !== '')
    .sort()
    .map((key) => `${key}=${params[key]}`)
    .join('&');

  return crypto.createHash('sha1').update(`${canonical}${secret}`).digest('hex');
}

/** POST a signed form to one of Cloudinary's endpoints. */
async function callCloudinary(endpoint, params, file = null) {
  const timestamp = Math.floor(Date.now() / 1000);
  const signed = { ...params, timestamp };

  const form = new FormData();
  for (const [key, value] of Object.entries(signed)) form.append(key, String(value));
  form.append('api_key', env.CLOUDINARY_API_KEY);
  form.append('signature', signParams(signed, env.CLOUDINARY_API_SECRET));
  if (file) form.append('file', new Blob([file.buffer], { type: file.mimetype }), 'upload');

  const response = await fetch(`${API_BASE}/${env.CLOUDINARY_CLOUD_NAME}/${endpoint}`, {
    method: 'POST',
    body: form,
  });

  const body = await response.json().catch(() => ({}));

  if (!response.ok) {
    /*
     * Cloudinary's own message, not the status code alone: "Invalid Signature"
     * and "Stale request" are different mistakes with different fixes, and a
     * bare 401 sends people to check credentials that are perfectly correct.
     * (A stale request means this server's clock is wrong.)
     */
    throw new Error(body?.error?.message ?? `Cloudinary responded ${response.status}`);
  }

  return body;
}

/**
 * A name for the stored asset, generated by us.
 *
 * The client's filename is never used anywhere in this module: `../../etc` and
 * `shell.php` are how path traversal and executable-upload attacks are spelled,
 * and a random name makes both impossible to express.
 *
 * @param {string|null} folder Already sanitised — see sanitiseFolder.
 */
function generateId(folder) {
  const month = new Date().toISOString().slice(0, 7);
  const name = crypto.randomBytes(16).toString('hex');

  // Filed under the category when the caller named one, so the media library
  // groups the way the menu does; by month otherwise, which is all a payment QR
  // or a storefront banner can meaningfully be sorted by.
  return folder ? `${folder}/${name}` : `${month}/${name}`;
}

/**
 * Reduce a caller-supplied folder name to something safe to put in a public id.
 *
 * This value reaches Cloudinary as part of the asset's path, and it arrives
 * from a form field, so it is untrusted. A name containing `../` would file the
 * upload outside this installation's folder — into another site's assets on a
 * shared account — and a leading slash would do the same. Rather than trying to
 * spot the dangerous spellings, everything outside `[a-z0-9-]` is discarded, so
 * no traversal can survive being expressed.
 *
 * Returns null for anything that reduces to nothing, which puts the upload back
 * on the month-based path rather than in a folder called "".
 */
export function sanitiseFolder(value) {
  if (typeof value !== 'string') return null;

  const cleaned = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);

  return cleaned || null;
}

/**
 * Recover a Cloudinary public id from one of its delivery URLs.
 *
 * A delivery URL looks like:
 *   https://res.cloudinary.com/<cloud>/image/upload/v1712345678/folder/name.png
 *   https://res.cloudinary.com/<cloud>/video/upload/w_400,c_fill/v1/a/b.mp4
 *
 * The public id is everything after the version segment, minus the extension —
 * and transformation segments (which sit between `upload` and the version) must
 * be dropped. Returns null for anything that is not a Cloudinary URL, which is
 * how a legacy `/uploads/...` path falls through to the local driver.
 *
 * @returns {{ publicId: string, resourceType: string } | null}
 */
export function parseCloudinaryUrl(url) {
  if (typeof url !== 'string') return null;

  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }

  if (!/(^|\.)cloudinary\.com$/i.test(parsed.hostname)) return null;

  const segments = parsed.pathname.split('/').filter(Boolean);
  const uploadAt = segments.indexOf('upload');
  if (uploadAt === -1) return null;

  // `image` / `video` / `raw` sits immediately before `upload`.
  const resourceType = segments[uploadAt - 1] ?? 'image';

  let rest = segments.slice(uploadAt + 1);
  // Skip the version marker and anything before it (transformations).
  const versionAt = rest.findIndex((segment) => /^v\d+$/.test(segment));
  if (versionAt !== -1) rest = rest.slice(versionAt + 1);

  if (rest.length === 0) return null;

  const publicId = decodeURIComponent(rest.join('/')).replace(/\.[^./]+$/, '');
  return publicId ? { publicId, resourceType } : null;
}

/**
 * Is this URL something we stored, and may therefore delete?
 *
 * Guards every deletion path. A product whose image is a hand-pasted external
 * URL, or one of the bundled `/images/...` assets that ship with the client,
 * must survive being replaced — deleting is only ever correct for an asset this
 * application created.
 */
export function isManagedAsset(url) {
  if (typeof url !== 'string' || !url) return false;
  if (parseCloudinaryUrl(url)) return true;
  return url.startsWith('/uploads/');
}

/** Absolute path for a local `/uploads/...` URL, or null if it escapes the root. */
function localPathFor(url) {
  const relative = url.replace(/^\/uploads\//, '');
  const resolved = path.resolve(UPLOAD_ROOT, relative);

  /*
   * Containment check. These URLs come out of the database, and a value like
   * `/uploads/../../src/server.js` would otherwise resolve to a real file that
   * `remove()` would happily unlink. Nothing writes such a row today; the check
   * costs nothing and means nothing ever can.
   */
  const root = path.resolve(UPLOAD_ROOT);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) return null;
  return resolved;
}

/**
 * Send a verified file to Cloudinary.
 *
 * Separate from saveUpload so it can be exercised without switching the whole
 * process onto the Cloudinary driver — the branch inside saveUpload is decided
 * once, at import time, from the environment, which would otherwise make this
 * code unreachable from any test that is not itself running against a real
 * Cloudinary account.
 *
 * @param {object} file `{ mimetype, buffer }`
 */
export async function uploadToCloudinary(file, { folder } = {}) {
  const resourceType = file.mimetype.startsWith('video/') ? 'video' : 'image';
  const publicId = `${env.CLOUDINARY_FOLDER}/${generateId(sanitiseFolder(folder))}`;

  const result = await callCloudinary(
    `${resourceType}/upload`,
    {
      public_id: publicId,
      // We name the asset; Cloudinary must not derive one from the upload.
      use_filename: false,
      unique_filename: false,
      // Never silently replace an existing asset — a public-id collision is a
      // bug worth hearing about, not something to paper over by overwriting
      // somebody else's photo.
      overwrite: false,
    },
    file,
  );

  /*
   * secure_url, never `url`. Cloudinary returns both, and the plain one is
   * http:// — which a browser on an https:// page blocks outright, so the
   * image simply never appears and nothing in the logs says why.
   */
  return { url: result.secure_url, publicId: result.public_id };
}

/**
 * Persist a verified upload.
 *
 * Called only after the signature check has confirmed the bytes match a type we
 * accept, so `mimetype` here is the type the content reported — not the one the
 * client claimed.
 *
 * @param {object} file    A multer file: `{ mimetype, buffer? , path? , size }`
 * @returns {Promise<{ url: string, publicId: string|null }>}
 */
export async function saveUpload(file, options = {}) {
  if (!file) throw new Error('saveUpload called without a file');

  if (isCloudinary) return uploadToCloudinary(file, options);

  // The local driver has already written the file to disk via multer's
  // diskStorage; the URL is simply where the static handler will serve it.
  const relative = path.relative(UPLOAD_ROOT, file.path).split(path.sep).join('/');
  return { url: `/uploads/${relative}`, publicId: null };
}

/**
 * Destroy one Cloudinary asset.
 *
 * Exported alongside uploadToCloudinary, and for the same reason: it is the
 * step that decides which asset disappears, so it deserves to be exercised
 * directly rather than only through a driver branch that a test process cannot
 * enter.
 *
 * @param {{ publicId: string, resourceType: string }} asset
 */
export async function destroyCloudinaryAsset({ publicId, resourceType }) {
  const result = await callCloudinary(`${resourceType}/destroy`, {
    public_id: publicId,
    // Purge the CDN too. Without this the old image keeps being served from
    // the edge for hours after it is gone from the account, which looks exactly
    // like a delete that silently failed.
    invalidate: true,
  });

  /*
   * `not found` counts as success. It means the asset is already gone — the
   * desired end state — and treating it as a failure would fill the log with
   * alarms every time a delete was retried or an admin removed the same image
   * from two records.
   */
  if (result?.result === 'ok' || result?.result === 'not found') return true;

  logger.warn('Cloudinary asset was not deleted', { publicId, result: result?.result });
  return false;
}

/**
 * Destroy a stored asset. Best effort, and deliberately non-throwing.
 *
 * Why it never throws: every caller reaches here after the database write that
 * matters has already succeeded. Turning "the old photo could not be deleted"
 * into a failed product update would roll back correct work and show the admin
 * an error for something that does not affect them. The leak is logged instead,
 * which is what makes it traceable and cleanable later.
 *
 * @returns {Promise<boolean>} whether the asset is now gone
 */
export async function removeAsset(url) {
  if (!isManagedAsset(url)) return false;

  const cloudinaryAsset = parseCloudinaryUrl(url);

  try {
    if (cloudinaryAsset) return await destroyCloudinaryAsset(cloudinaryAsset);

    const absolute = localPathFor(url);
    if (!absolute) {
      logger.warn('Refused to delete an upload path outside the upload root', { url });
      return false;
    }
    await fs.unlink(absolute);
    return true;
  } catch (error) {
    // ENOENT: already gone locally. Same reasoning as `not found` above.
    if (error?.code === 'ENOENT') return true;
    logger.error('Failed to delete a stored asset', { url, message: error.message });
    return false;
  }
}

export default { saveUpload, removeAsset, isManagedAsset, parseCloudinaryUrl, isCloudinary };
