/**
 * POS routes — mounted at {API_PREFIX}/pos.
 * ---------------------------------------------------------------------------
 * Every route here requires `authenticatePos`, which verifies against the POS
 * token secret. A website access token fails signature verification here, so a
 * signed-in customer can never ring up a sale, and a stolen till token cannot
 * be replayed against customer endpoints.
 *
 * What a till can see is decided here, not on the till: the store comes from
 * the POS token, the menu scope from the terminal record. Neither is a request
 * parameter, so there is nothing for the client to widen.
 */
import { Router } from 'express';
import { z } from 'zod';

import { validate } from '../../middleware/validate.middleware.js';
import { authenticatePos } from '../../middleware/auth.middleware.js';
import { asyncHandler } from '../../core/utils/asyncHandler.js';
import { sendSuccess, sendCreated } from '../../core/http/ApiResponse.js';
import { PERMISSIONS, userCan } from '../../core/constants/roles.js';
import { posService, POS_PAYMENT_METHODS, POS_ORDER_TYPES } from './pos.service.js';
import { shiftService } from './shift.service.js';
import { Terminal } from './terminal.model.js';
import { catalogService } from '../catalog/catalog.service.js';
import { MOVEMENT_TYPES } from './shift.model.js';

const router = Router();

// One gate for the whole surface, rather than repeating it per route — a route
// added later is protected by default instead of by remembering.
router.use(authenticatePos);

const objectId = z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid id');

const saleItems = z
  .array(
    z.object({
      productId: objectId,
      quantity: z.coerce.number().positive('Quantity must be greater than zero'),
    }),
  )
  .min(1, 'Add at least one item')
  .max(100, 'Too many lines on one bill');

const customerBody = z
  .object({
    name: z.string().trim().max(120).optional(),
    phone: z.string().trim().max(20).optional(),
  })
  .optional();

/** Fields shared by "pay now" and "send to kitchen". */
const ticketFields = {
  // Generated by the till before sending, so a retry carries the same key and
  // cannot ring the sale up twice.
  saleRef: z.string().trim().min(8, 'Missing sale reference').max(64),
  items: saleItems,
  discount: z.coerce.number().min(0).default(0),
  customer: customerBody,
  orderType: z.enum(POS_ORDER_TYPES).optional(),
  tableNumber: z.string().trim().max(20).optional(),
  kitchenNote: z.string().trim().max(300).optional(),
};

/** Permission checks against the cashier's own grants (the POS token's user). */
const can = (req, permission) => userCan(req.userDoc, permission);

/* ------------------------------------------------------------------------ */
/* This till                                                                */
/* ------------------------------------------------------------------------ */

/**
 * Who and where this till is, and what it sells — the POS header, and the
 * reason a cashier's menu looks the way it does.
 */
router.get(
  '/terminal',
  asyncHandler(async (req, res) => {
    const terminal = await Terminal.findOne({ code: req.pos.terminalId })
      .select('code name location store menuMode')
      .populate('store', 'name code')
      .lean();

    return sendSuccess(res, {
      message: 'OK',
      data: {
        code: req.pos.terminalId,
        name: terminal?.name ?? req.pos.terminalId,
        location: terminal?.location ?? null,
        store: terminal?.store ? { id: String(terminal.store._id), name: terminal.store.name } : null,
        menuMode: terminal?.menuMode ?? 'all',
        cashier: { id: req.pos.cashierId, name: req.pos.cashierName },
        // What the till UI should offer. Server-enforced regardless.
        permissions: {
          discount: can(req, PERMISSIONS.POS_DISCOUNT),
          viewAllSales: can(req, PERMISSIONS.POS_VIEW_ALL_SALES),
          cancelOrders: can(req, PERMISSIONS.ORDER_CANCEL),
        },
      },
    });
  }),
);

/* ------------------------------------------------------------------------ */
/* The till's own menu                                                      */
/* ------------------------------------------------------------------------ */

router.get(
  '/products',
  validate({
    query: z.object({
      search: z.string().trim().max(120).optional(),
      category: z.string().trim().optional(),
      limit: z.coerce.number().int().positive().max(200).default(100),
    }),
  }),
  asyncHandler(async (req, res) => {
    const menu = await posService.menuScope(req.pos);
    const { items } = await catalogService.listProducts({
      // The counter grid shows only what is sold at a counter.
      channel: 'pos',
      ...req.query,
      store: req.pos.storeId,
      menuFilter: menu.filter,
    });
    return sendSuccess(res, { message: 'OK', data: items });
  }),
);

/**
 * Scanned-code lookup, scoped to this counter and this till's menu.
 * Declared before any `/products/:something` route so "resolve" is never read
 * as a slug.
 */
router.get(
  '/products/resolve',
  validate({ query: z.object({ code: z.string().trim().min(1, 'No code supplied').max(64) }) }),
  asyncHandler(async (req, res) => {
    const menu = await posService.menuScope(req.pos);
    return sendSuccess(res, {
      message: 'OK',
      data: await catalogService.resolveScannedCode(req.query.code, {
        store: req.pos.storeId,
        channel: 'pos',
        menuFilter: menu.filter,
      }),
    });
  }),
);

router.get(
  '/categories',
  asyncHandler(async (req, res) => {
    const menu = await posService.menuScope(req.pos);
    return sendSuccess(res, {
      message: 'OK',
      data: await catalogService.listCategories({
        store: req.pos.storeId,
        channel: 'pos',
        menuFilter: menu.filter,
      }),
    });
  }),
);

// --- Price a basket (no sale recorded) -------------------------------------
router.post(
  '/quote',
  validate({
    body: z.object({ items: saleItems, discount: z.coerce.number().min(0).default(0) }),
  }),
  asyncHandler(async (req, res) => {
    const menu = await posService.menuScope(req.pos);
    return sendSuccess(res, {
      message: 'OK',
      data: await posService.quote(req.body, { store: req.pos.storeId, menu }),
    });
  }),
);

/* ------------------------------------------------------------------------ */
/* Selling                                                                  */
/* ------------------------------------------------------------------------ */

// --- Pay now (and, with the kitchen on, send to the kitchen) ---------------
router.post(
  '/sales',
  validate({
    body: z.object({
      ...ticketFields,
      paymentMethod: z.enum(POS_PAYMENT_METHODS),
      tendered: z.coerce.number().min(0).optional(),
    }),
  }),
  asyncHandler(async (req, res) => {
    const { slip, duplicate } = await posService.recordSale(req.body, req.pos, {
      canDiscount: can(req, PERMISSIONS.POS_DISCOUNT),
    });

    // 200 rather than 201 on a duplicate: nothing new was created, and the
    // till needs to know it is looking at the original sale.
    return duplicate
      ? sendSuccess(res, { message: 'This sale was already recorded', data: slip })
      : sendCreated(res, slip, 'Sale recorded');
  }),
);

// --- Send to kitchen, pay later ---------------------------------------------
router.post(
  '/orders',
  validate({ body: z.object(ticketFields) }),
  asyncHandler(async (req, res) => {
    const { slip, duplicate } = await posService.fireOrder(req.body, req.pos, {
      canDiscount: can(req, PERMISSIONS.POS_DISCOUNT),
    });
    return duplicate
      ? sendSuccess(res, { message: 'This ticket was already sent', data: slip })
      : sendCreated(res, slip, `Ticket #${slip.ticketNumber} sent to the kitchen`);
  }),
);

// --- This counter's live tickets ---------------------------------------------
router.get(
  '/orders/open',
  asyncHandler(async (req, res) =>
    sendSuccess(res, { message: 'OK', data: await posService.listOpenOrders(req.pos) }),
  ),
);

router.post(
  '/orders/:id/pay',
  validate({
    params: z.object({ id: objectId }),
    body: z.object({
      paymentMethod: z.enum(POS_PAYMENT_METHODS),
      tendered: z.coerce.number().min(0).optional(),
    }),
  }),
  asyncHandler(async (req, res) => {
    const { slip, duplicate } = await posService.payOrder(req.params.id, req.body, req.pos);
    return sendSuccess(res, {
      message: duplicate ? 'This ticket was already paid' : 'Payment recorded',
      data: slip,
    });
  }),
);

router.post(
  '/orders/:id/serve',
  validate({ params: z.object({ id: objectId }) }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, { message: 'Handed over', data: await posService.serveOrder(req.params.id, req.pos) }),
  ),
);

router.post(
  '/orders/:id/void',
  validate({ params: z.object({ id: objectId }) }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, {
      message: 'Ticket voided — items returned to stock',
      data: await posService.voidOrder(req.params.id, req.pos, {
        canCancel: can(req, PERMISSIONS.ORDER_CANCEL),
      }),
    }),
  ),
);

/* ------------------------------------------------------------------------ */
/* History                                                                  */
/* ------------------------------------------------------------------------ */

router.get(
  '/sales',
  validate({
    query: z.object({
      limit: z.coerce.number().int().positive().max(100).default(25),
      // "Only my sales" — a cashier reconciling their own drawer.
      mine: z.coerce.boolean().default(false),
    }),
  }),
  asyncHandler(async (req, res) => {
    /*
     * `pos.view_all_sales` decides whether "everyone's sales on this till" is
     * an option at all. Without it the list is the cashier's own, whatever the
     * request asked for — the permission was in the matrix and enforced nowhere.
     */
    const mine = req.query.mine || !can(req, PERMISSIONS.POS_VIEW_ALL_SALES);
    return sendSuccess(res, {
      message: 'OK',
      data: await posService.listSales({
        terminalId: req.pos.terminalId,
        cashierId: req.pos.cashierId,
        limit: req.query.limit,
        mine,
      }),
    });
  }),
);

// --- Reprint ----------------------------------------------------------------
router.get(
  '/sales/:id',
  validate({ params: z.object({ id: objectId }) }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, {
      message: 'OK',
      data: await posService.getSale(req.params.id, {
        terminalId: req.pos.terminalId,
        cashierName: req.pos.cashierName,
      }),
    }),
  ),
);

// --- Today's takings for this till -----------------------------------------
router.get(
  '/summary',
  asyncHandler(async (req, res) =>
    sendSuccess(res, {
      message: 'OK',
      data: await posService.todaySummary({
        terminalId: req.pos.terminalId,
        cashierId: req.pos.cashierId,
      }),
    }),
  ),
);

/* ------------------------------------------------------------------------ */
/* Shift and cash drawer                                                    */
/* ------------------------------------------------------------------------ */

router.get(
  '/shift',
  asyncHandler(async (req, res) =>
    sendSuccess(res, { message: 'OK', data: await shiftService.current(req.pos) }),
  ),
);

router.post(
  '/shift/open',
  validate({
    body: z.object({
      openingFloat: z.coerce.number().min(0, 'Enter the cash in the drawer').max(1_000_000),
    }),
  }),
  asyncHandler(async (req, res) =>
    sendCreated(res, await shiftService.open(req.body, req.pos), 'Shift opened'),
  ),
);

router.post(
  '/shift/movement',
  validate({
    body: z.object({
      type: z.enum(MOVEMENT_TYPES),
      amount: z.coerce.number().int().positive('Enter an amount').max(1_000_000),
      // Required: an unexplained movement is indistinguishable from theft.
      reason: z.string().trim().min(3, 'Say what this is for').max(200),
    }),
  }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, { message: 'Recorded', data: await shiftService.addMovement(req.body, req.pos) }),
  ),
);

router.post(
  '/shift/close',
  validate({
    body: z.object({
      countedCash: z.coerce.number().min(0, 'Enter the counted total').max(10_000_000),
      note: z.string().trim().max(300).optional(),
    }),
  }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, { message: 'Shift closed', data: await shiftService.close(req.body, req.pos) }),
  ),
);

router.get(
  '/shift/history',
  validate({ query: z.object({ limit: z.coerce.number().int().positive().max(50).default(20) }) }),
  asyncHandler(async (req, res) =>
    sendSuccess(res, {
      message: 'OK',
      data: await shiftService.history({ terminalId: req.pos.terminalId, ...req.query }),
    }),
  ),
);

export default router;
